name: CI

on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@next

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@next

  test_redis:
    uses: adonisjs/cache/.github/workflows/test_redis.yml@1.x

  test_postgres:
    uses: adonisjs/cache/.github/workflows/test_postgres.yml@1.x

  test_mysql:
    uses: adonisjs/cache/.github/workflows/test_mysql.yml@1.x
