name: CI

on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@main

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    timeout-minutes: 10
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysql
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: FORCE_COLOR=1 npm test
